// backend/src/App.tsx
import { useEffect, useState } from 'react';

interface Todo {
  id: number;
  title: string;
  completed: boolean;
}

function App() {
  const [todos, setTodos] = useState<Todo[]>([]);

  useEffect(() => {
    fetch('http://localhost:3000/todos')
      .then(res => res.json())
      .then(data => setTodos(data))
      .catch(err => console.error('データ取得失敗:', err));
  }, []);

  return (
    <div style={{ padding: '2rem' }}>
      <h1>✅ Todo 一覧</h1>
      <ul>
        {todos.map(todo => (
          <li key={todo.id}>
            <span>{todo.title}</span>
            {todo.completed ? ' ✅' : ' ⬜️'}
          </li>
        ))}
      </ul>
    </div>
  );
}

export default App;

// frontend/src/App.vue
<script>
import { ref, onMounted } from 'vue'

export default {
  setup() {
    const todos = ref([])

    onMounted(async () => {
      try {
        const res = await fetch('http://localhost:3000/todos')
        todos.value = await res.json()
      } catch (e) {
        console.error('データ取得失敗:', e)
      }
    })

    return {
      todos
    }
  }
}
</script>

<template>
  <div style="padding: 2rem">
    <h1>✅ Todo一覧</h1>
    <ul>
      <li v-for="todo in todos" :key="todo.id">
        {{ todo.title }} {{ todo.completed ? '✅' : '⬜️' }}
      </li>
    </ul>
  </div>
</template>

<style>
body {
  font-family: sans-serif;
}
</style>
